baseURL = "http://tech.aminpartners.com/"
languageCode = "ko-kr"
title = "AMIN PARTNERS Tech blog"
theme = "hugo-nuo"
publishDir = "public"
favicon = "test.png"

[params]
  author = "아민 파트너스"
  avatar = "/logo700.png"
  favicon = "test.png"

[[menu.main]]
  name = "홈"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "공식 사이트"
  weight = 20
  identifier = "site"
  url = "http://www.aminpartners.com/"

[[menu.main]]
  name = "태그"
  weight = 30
  identifier = "tags"
  url = "/tags/"
